const TITLE_FORM_LOGIN = "Login";
const TITLE_FORM_REGISTER = "Register";
const TITLE_FORM_OTP = "Enter Your OTP";
const TITLE_FORM_STAGE = "Stage";
const TITLE_FORM_FORGOT_PASSWORD = "Forgot Password";
const TITLE_FORM_PROMOTION = "Promotion List";
const TITLE_FORM_FAKE_INFORMATION = "Order Information";

export {
    TITLE_FORM_LOGIN,
    TITLE_FORM_REGISTER,
    TITLE_FORM_OTP,
    TITLE_FORM_STAGE,
    TITLE_FORM_FORGOT_PASSWORD,
    TITLE_FORM_PROMOTION,
    TITLE_FORM_FAKE_INFORMATION,
}